export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/'
export const PROFILE_ROUTE = '/profile'
export const POST_ROUTE = '/post'
export const ADD_POST_ROUTE = '/create'